spring:
  datasource:
    url: jdbc:h2:mem:ecommerce_db
    username: dbuser
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        "[globally_quoted_identifiers]": true
        "[format_sql]": true
  h2:
    console:
      enabled: true
      path: /h2_console
      settings:
        trace: false
        #web-allow-others: false